# Build in Netlify even if there is 'no content change'.
[build]
  ignore = "/bin/false"

[build.environment]
  DRUPAL_URL="https://headless-oktainc.pantheonsite.io"
  GATSBY_DRUPAL_URL="https://headless-oktainc.pantheonsite.io"
  DRUPAL_LANGUAGE="EN"
  DRUPAL_PATH="/"

[context.asset-prefix-okta.environment]
  PREFIX_PATHS = "true"

[context.ciam.environment]
  PREFIX_PATHS = "true"
  GATSBY_OKTA_SESSION_URL="https://ciam.oktatest.com/oktaapi/myokta/session"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[context.production.environment]
  GATSBY_OKTA_SESSION_URL="https://www.okta.com/oktaapi/myokta/session"

[context.deploy-preview.environment]
  GATSBY_OKTA_SESSION_URL="https://ciam.oktatest.com/oktaapi/myokta/session"

[context.branch-deploy]
  GATSBY_OKTA_SESSION_URL="https://www.oktatest.com/oktaapi/myokta/session"

